---
title: ""
date: October 4th 2025
author: []

institute: {}

header-includes:
  - \usepackage{setspace}
  - \usepackage{fancyhdr}
  - \usepackage[left]{lineno}
  - \doublespacing

# bibliography: ./bibliography/your_reference_here.json
# csl: ./bibliography/your_csl_here.csl

mainfont: Times New Roman
fontsize: 12pt

params:
  input_document: NA

output:
  word_document:
    toc: false
    number_sections: false
    reference_docx: "./support-docs/doc_base.docx"
  pdf_document:
    toc: false
    number_sections: false
    latex_engine: xelatex
---

 

\pagestyle{fancy}

\fancyhead[L]{Oscar Ramfelt}

\fancyhead[R]{Design thinking process: Individual reflection - 04-10-2025}

# From Solution-First to Problem-Led

At the start of the design thinking process, I was heavily focused on solutions rather than truly understanding the user’s problems. Instead of exploring their needs, I concentrated on developing a solution based on assumptions about what the problem was. Through the design thinking process, I realized the importance of the earlier stages—steps that ensure a deeper understanding of the user and the problem clearly they have. These early stages help prevent wasted time and resources on creating solutions that may not actually be needed.

The worksheet "Trends & Knowledge Map" was one of the key templates that helped clarify the process for me. It acted as a clear methodology from which to analyze the problem/challenge from the user's point of view and the complex set of aspects that may influence a user. This template gave me and my group a shared understanding to identify a user’s needs and kept discussions from ballooning into everything and therefore nothing. This was useful when we were trying to identify an initial problem definition for the challenges our users, i.e. researchers have. By using the template we could organize our different ideas and clearly identify what aspects of the researcher's needs that we should take into consideration.

Moving forward with our group's project I think we will rely heavily on the different sections of the double diamond design thinking methodology. Group projects can often suffer from ambiguity about what the goals are. I think that the diamonds provide a straightforward way to support the group in findings an agreement on which needs to focus on.

A key challenge for us will be resisting the urge to move too quickly. In today’s context, it often feels as though every problem calls for the immediate development of a new app. It is tempting to jump from identifying a problem straight to proposing a solution and then rushing into implementation. However, our first test run of the design thinking method showed that this approach carries significant risks. By slowing down and carefully working through each stage of the process, we gain a fuller understanding of both the problems and the potential solutions. This allows us to choose the best possible approach within the constraints of our time and resources.